name: HTML

on:
  push:
    branches:
    - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Selective installation of rdflib-5.0.0
      run: pip install rdflib==5.0.0
    - name: Install wheel and pyLODE 
      run: pip install wheel pylode
    - name: Install requests and argparse 
      run: pip install requests argparse
    - name: Build HTML
      run: mkdir -p public && python /home/runner/.local/lib/python3.10/site-packages/pylode/cli.py -v -o public/index-develop.html pmdco_core.ttl && ls public 
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
