name: HTML

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: retrieve widoco
      run: wget -O widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.17/widoco-1.4.17-jar-with-dependencies.jar
    - name: Check Dir
      run: ls public
    - uses: actions/checkout@v3
      with:
        ref: main
        path: main
    - name: Build HTML for main
 #     run: python /home/runner/.local/lib/python3.10/site-packages/pylode/cli.py -o public/index.html main/pmdco_core.ttl       
      
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
